# Generated by Django 5.0.3 on 2024-03-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='site',
            field=models.CharField(choices=[('Main', 'Main'), ('Canuto', 'Canuto'), ('Dumingag', 'Dumingag'), ('Pagadian', 'Pagadian')], max_length=100),
        ),
    ]
