# Generated by Django 5.0.3 on 2024-03-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_is_librarian_librarian_is_librarian_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian',
            name='email',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='librarian',
            name='facebook_link',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
