# Generated by Django 5.0.3 on 2024-04-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_librarian_email_librarian_facebook_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitors',
            new_name='Visit',
        ),
    ]
