# Generated by Django 5.0.4 on 2024-04-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_visit_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=250)),
                ('month', models.DateField()),
                ('startDatetime', models.TimeField()),
                ('endDatetime', models.TimeField()),
            ],
        ),
    ]
